pcall(require, "luarocks.loader")

require("modules.errors")
require("modules.config")
require("modules.menu")
require("modules.bar")
require("modules.keys")
require("modules.rules")
require("modules.signals")
require("modules.autorun")
